---
name: Tor
version: dev
slug: tor
description: Protect your privacy and access Home Assistant via Tor.
url: https://github.com/hassio-addons/addon-tor
startup: services
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
init: false
ports:
  9050/tcp: 9050
  9001/tcp: 9001
ports_description:
  9050/tcp: Tor SOCKS proxy port
  9001/tcp: Tor OR Port
map:
  - ssl:rw
options:
  socks: false
  hidden_services: true
  stealth: false
  client_names: []
  ports:
    - "8123"
  relay: false
  relayBandwidthRate: "1 MB"
  relayBandwidthBurst: "1 MB"
  relayNickName: ""
  relayOrPort: '9001'
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  socks: bool
  hidden_services: bool
  relay: bool
  stealth: bool
  client_names:
    - match(^[A-Za-z0-9+-_]{1,16}$)
  relayNickName:
    - match(^[A-Za-z0-9+-_]{1,16}$)
  ports:
    - match(^(.*:)?(?:[0-9]{1,4}|[1-5][0-9]{4}|6[0-4][0-9]{3}|65[0-4][0-9]{2}|655[0-2][0-9]|6553[0-5])?$)